spring:
  datasource:
    url: jdbc:postgresql://db:5432/appdb
    username: ${POSTGRES_USER:app}
    password: ${POSTGRES_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 1000
      validation-timeout: 1000
      maximum-pool-size: 10
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 60000
      leak-detection-threshold: 10000
  sql:
    init:
      mode: never
      continue-on-error: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,chaosmonkey
  endpoint:
    health:
      show-details: always
    chaosmonkey:
      enabled: true

chaos:
  monkey:
    enabled: false
    watcher:
      restController: true
    assaults:
      level: 3
      latencyActive: false
      exceptionsActive: false
      killApplicationActive: false
      restartApplicationActive: false
