spring:
  config:
    activate:
      on-profile: chaos-monkey
  application:
    name: dungeon-game-kata
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: app
    password: secret
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
#      mode: always
      continue-on-error: true
server:
  port: 8080

chaos:
  monkey:
    enabled: true

logging:
  level:
    de.codecentric.spring.boot.chaos.monkey: DEBUG
    org.springframework.boot.autoconfigure: DEBUG