spring:
  application:
    name: dungeon-game-kata
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: app
    password: secret
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
#      mode: always
      continue-on-error: true
server:
  port: 8080
