spring:
  application:
    name: dungeon-game-kata
  datasource:
    url: jdbc:postgresql://db:5432/appdb # 'db' = service name on docker-compose
    username: app
    password: secret
    hikari:
      connection-timeout: 1000
      validation-timeout: 1000
      maximum-pool-size: 10
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 60000
      leak-detection-threshold: 10000

  sql:
    init:
      mode: never
      continue-on-error: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        connection:
          provider_disables_autocommit: true
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: none

server:
  address: 0.0.0.0
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,chaosmonkey
  endpoint:
    health:
      show-details: always
    chaosmonkey:
      enabled: true

chaos:
  monkey:
    enabled: false
    watcher:
      restController: true
      service: true
    assaults:
      level: 3
      latencyActive: false
      exceptionsActive: false
      killApplicationActive: false
      restartApplicationActive: false
